# Generated by Django 4.2.5 on 2023-09-08 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=10, verbose_name='Короткий код')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование модальности')),
            ],
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_fio', models.CharField(max_length=250, verbose_name='ФИО пациента')),
                ('patient_birthdate', models.DateField(verbose_name='Дата рождения пациента')),
                ('study_uid', models.UUIDField(verbose_name='Идентификатор исследования во внешней системе')),
                ('study_date', models.DateTimeField(verbose_name='Дата и время исследования')),
                ('study_modality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='test_datatable.modalities', verbose_name='Модальность исследования')),
            ],
        ),
    ]
